name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Ajusta la versión de Flutter según tu necesidad

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: AppTask.apk
          path: app/build/outputs/apk/debug/app-debug.apk